### ISSUE TITLE
Discord forum channels

### ISSUE THREAD

**Issue by Pyro57000** [mautrix/discord#124] opened 2023-10-15 13:38 UTC
I know there isn't like a forum standard in matrix as of yet, but being able to handle forum channels either by using nested packs or by creating threads would be amazing.

For example let's say we have a discord forum channel called guild-forum and in there we have two topics, cool-stuff and cringe-stuff, both have several replies.

One way we could handle this in matrix would be to create a space for the channel called guild-forum and then create two nested spaces called cool-stuff and cringe-stuff, then put the replies to the forum posts there.

Another way to potentially handle these would be to create the space for the channel and then send a message for each forum topic and create a thread and send the replies via the thread.

Out of the two I think I like the space idea better as it seems more clients support nested spaces than do threads, but threads would replicate what discord look like better.

**Comment by tulir** [comment] 2023-10-15 13:40
Duplicate of #101

**Closed by tulir** 2023-10-15 13:40 UTC
Labels: enhancement
