### ISSUE TITLE
set /myroomnick with server nickname

### ISSUE THREAD

**Issue by kylrth** [mautrix/discord#120] opened 2023-09-28 19:32 UTC
I bridge a Discord guild where people's server nicknames are important, and it would be very nice to be able to see those nicknames on the Matrix side, instead of whatever their general Discord display name is.

**Comment by tulir** [comment] 2023-09-28 19:37
Duplicate of #42

**Closed by tulir** 2023-09-28 19:37 UTC
Labels: enhancement

**Comment by kylrth** [comment] 2023-09-28 19:49
oops sorry
